version: '3.8'
services:    
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: task_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:   
      - ./db:/docker-entrypoint-initdb.d/  
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - '8001:8001'
    depends_on:
      - cache
  task-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    entrypoint: ["/usr/src/app/entrypoint.sh"]
    env_file:
      - ./.env
    depends_on:
      - db
      - cache
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
volumes:
  db:
    driver: local
  cache:
    driver: local